image: maven:3.6.0-jdk-8


variables:
  MAVEN_OPTS: "-Dhttps.protocols=TLSv1.2 -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"
  MAVEN_CLI_OPTS: "-f ./mockup-editor/pom.xml --batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true"

cache:
  key: "$CI_JOB_NAME"
  paths:
    - .m2/repository
    - "*/target"
    - "*/*/*/*/*/node_modules"

build:
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS compile
  only:
    refs:
      - master
      - devel

test:
  stage: test
  script:
    - mvn $MAVEN_CLI_OPTS test
  only:
    refs:
      - master
      - devel


